sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: sTmucJJfAw/qX5nBIAvSuLo4BdRUREhDG0zS6/16F0QJqhx0sHMSNISQvEMGyd8r5SvmW4UimmeJMV5Ln2ij2IR61dmgo9IS3mFuo6BI1TXYErK0aOS63TulgAjL/v8/M7K62diqatRtWDOPg6lSIviGaoo8xbSERKyIsimMyPscLBtn8dL9mDz0J7tbYZNa2BuR7WEX1ZXHNZfQis8BoB9BnmVzRJSeX8l5SNT+EE3Y6dMRfX6TAUOV0QUJn4V5QzpVG+tZb4soQUx+XHVpHaCavZ7skeqVNNbzKis/gSiDLB73YOknzXXSwwCl5jngKehLV8SLOFx7fRaqzFuf5hLlLtosZ355dJoOR4M5frzCG2A62GGUjBwLxrfgejlt6PGCXYSRaMR8NBF8j3F2dk/lk89v0yb/8/CQq71m3yuvA2Ik9Mn+mX8iUFN05DMQM4D9j1DuUwAr5ZTn3xZtQi4RRDJHfeVtkuw1+h8Fd4q1TCbQFQeq+8Z+ehNBP5u0i4/gZSL/FO9kjRe+jtGHt3kI6PS9Gk7Zh1XFSKIw7rbsixDTDWNjSATwC8oNRBDrP6xw2gdrNOimZbQZmYgMJKu+MhDu/oQyQVF1VJ3R6zYNVqiFwI5yZa6N/9cdE5GqSuUFcThMeBKzSUp7Wz7bHzpD007EbXFkmu2iAnJMKgY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Man-in-Lower-Ten_1869
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy